[package]
name = "grz-check"
version = "0.2.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
description = "grz-check is a tool for validating incoming files of Modellvorhaben ยง64e submissions to Genomrechenzentren (GRZ) in Germany."
homepage = "https://github.com/BfArM-MVH/grz-tools/tree/main/packages/grz-check"
repository = "https://github.com/BfArM-MVH/grz-tools"
readme = "README.md"
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
noodles = { version = "0.100.0", features = ["sam", "bam", "fastq", "bgzf"] }
niffler = "3.0.0"
rayon = "1.10.0"
indicatif = { version = "0.18.0", features = ["rayon", "improved_unicode"] }
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.10.9"
serde_json = "1.0.140"
itertools = "0.14.0"
ctrlc = "3.4.7"

[dev-dependencies]
tempfile = "3.20"
flate2 = "1.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
