# GRZ crypt4gh public key
grz_public_key: |2
  -----BEGIN CRYPT4GH PUBLIC KEY-----
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
  -----END CRYPT4GH PUBLIC KEY----

## Or alternatively provide the path to the crypt4gh public key of the recipient (the associated GRZ).
# grz_public_key_path: 'path/to/public/key.pub'

## Uncomment the following line if you wish to be able to decrypt the submission.
# grz_private_key_path: 'path/to/private/key'

## Uncomment the following line if you wish to sign the submission.
# submitter_private_key_path: 'path/to/private/key'

s3_options:
  endpoint_url: 'https://your-s3-url'
  bucket: 'your-s3-bucket-name'
  access_key: 'your-s3-bucket-key'
  secret: 'your-s3-bucket-secret'

## optional parameters
# region_name: 'your-s3-region-name'
# api_version: 'your-s3-api-version'
# session_token: 'your-s3-session-token'
# proxy_url: 'your-proxy-url'
# use_ssl: true  # enabled by default
