[project]
name = "grz-common"
description = "Common library for grz applications"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Koray Kirli", email = "koraykirli@gmail.com" },
    { name = "Mathias Lesche", email = "mathias.lesche@tu-dresden.de" },
    { name = "Florian R. HÃ¶lzlwimmer", email = "git.ich@frhoelzlwimmer.de" },
    { name = "Till Hartmann", email = "till.hartmann@bih-charite.de" },
    { name = "Thomas Sell", email = "thomas.sell@bih-charite.de" },
    { name = "Travis Wrightsman", email = "travis.wrightsman@uni-tuebingen.de" }
]
dynamic = ["version"]
dependencies = [
    "boto3 >=1.36,<2",
    "click >=8.2,<9",
    "crypt4gh >=1.7,<2",
    "jsonschema >=4.23.0,<5",
    "pyyaml >=6.0.2,<7",
    "tqdm >=4.66.5,<5",
    "pydantic >=2.9.2,<2.10",
    "pydantic-settings >=2.9.0,<2.10",
    "platformdirs >=4.3.6,<5",
    "grz-pydantic-models >=2.0.0",
    "pysam ==0.23.*",
    "rich ==13.*",
    "requests >=2.32.3,<3",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
requires-python = ">=3.12"
keywords = ["GRZ", "GDC", "S3"]

[dependency-groups]
dev = ["tox", "tox-uv"]

[tool.uv.sources]
grz-pydantic-models = { path = "../grz-pydantic-models", editable = true }

[project.urls]
Homepage = "https://github.com/BfArM-MVH/grz-tools"
Repository = "https://github.com/BfArM-MVH/grz-tools"
Documentation = "https://github.com/BfArM-MVH/grz-tools/tree/main/packages/grz-common"
Issues = "https://github.com/BfArM-MVH/grz-tools/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/grz_common"]

[tool.hatch.version]
path = "src/grz_common/__init__.py"
