[project]
name = "grzctl"
description = "Control CLI for GRZ administrators."
readme = "README.md"
license = "MIT"
authors = [
    { name = "Koray Kirli", email = "koraykirli@gmail.com" },
    { name = "Mathias Lesche", email = "mathias.lesche@tu-dresden.de" },
    { name = "Florian R. HÃ¶lzlwimmer", email = "git.ich@frhoelzlwimmer.de" },
    { name = "Till Hartmann", email = "till.hartmann@bih-charite.de" },
    { name = "Thomas Sell", email = "thomas.sell@bih-charite.de" },
    { name = "Travis Wrightsman", email = "travis.wrightsman@uni-tuebingen.de" }
]
dynamic = ["version"]
dependencies = [
    "boto3 >=1.36,<2",
    "click >=8.2,<9",
    "crypt4gh >=1.7,<2",
    "jsonschema >=4.23.0,<5",
    "pyyaml >=6.0.2,<7",
    "tqdm >=4.66.5,<5",
    "pydantic >=2.9.2,<2.10",
    "pydantic-settings >=2.9.0,<2.10",
    "platformdirs >=4.3.6,<5",
    "pysam ==0.23.*",
    "rich ==13.*",
    "requests >=2.32.3,<3",
    "grz-db >=0.2.1",
    "grz-common >=1.0.3,<2",
    "grz-cli >=1.0.0",
    "grz-pydantic-models >=2.1.0,<3"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
requires-python = ">=3.12"
keywords = ["GRZ", "GDC", "S3"]

[tool.uv.sources]
grz-common = { path = "../grz-common", editable = true }
grz-cli = { path = "../grz-cli", editable = true }
grz-db = { path = "../grz-db", editable = true }
grz-pydantic-models = { path = "../grz-pydantic-models", editable = true}

[tool.tox.env_run_base]
runner = "uv-venv-lock-runner"
description = "run unit tests"
dependency_groups = ["test"]
commands = [["pytest", { replace = "posargs", default = ["tests"], extend = true }]]

[project.urls]
Homepage = "https://github.com/BfArM-MVH/grz-tools"
Repository = "https://github.com/BfArM-MVH/grz-tools"
Documentation = "https://github.com/BfArM-MVH/grz-tools/tree/main/packages/grzctl"
Issues = "https://github.com/BfArM-MVH/grz-tools/issues"

[project.scripts]
grzctl = "grzctl.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/grzctl/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/grzctl"]

[dependency-groups]
dev = ["tox", "tox-uv"]
test = [
    "pytest",
    "pytest-mock",
    "pytest-cov",
    "pytest-sugar",
    "moto[s3]",
    "numpy",
    "grz-common",
    "grzctl",
    "grz-cli"
]
