name: Publish Rust Crate to Crates.io

on:
  push:
    tags:
      - 'grz-check-v[0-9]+.[0-9]+.[0-9]+*'

env:
  RUST_TOOLCHAIN_VERSION: "1.89.0"

jobs:
  publish-to-crates-io:
    name: Build & Publish grz-check
    runs-on: ubuntu-latest
    if: "startsWith(github.ref_name, 'grz-check')"
    environment:
      name: crates.io
      url: https://crates.io/crates/grz-check
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}

      - name: Publish grz-check to crates.io
        working-directory: packages/grz-check
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}